 engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - ruby
      - javascript
    exclude_paths:
    - app/assets/javascripts/bootstrap.js
    - app/assets/javascripts/jquery.js
    - app/assets/javascripts/jstz.js
    - app/assets/javascripts/lightbox.js
    - "db/"
    - "log/"
    - public/design_test/jquery-1.5.2.min.js
    - "tmp/"
    - "test/"
  eslint:
    enabled: true
  fixme:
    enabled: true
    checks:
      XXX:
        enabled: false
  markdownlint:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.js"
  - "**.md"
  - "**.rake"
  - "**.rb"
  - "**.scss"
exclude_paths:
- app/assets/javascripts/bootstrap.js
- app/assets/javascripts/jquery.js
- app/assets/javascripts/jstz.js
- app/assets/javascripts/lightbox.js
- app/classes/query/modules/serialization.rb
- "db/"
- "log/"
- public/design_test/jquery-1.5.2.min.js
- "tmp/"


######################## Classic configuration ##########################
# Kept for convenience in case we decide to drop Engine-Based configuration
# languages:
#  JavaScript: true
#  Ruby: true
# exclude_paths:
# - public/design_test/jquery-1.5.2.min.js
# - app/assets/javascripts/bootstrap.js
# - app/assets/javascripts/jquery.js
# - app/assets/javascripts/jstz.js
# - app/assets/javascripts/lightbox.js
# - app/classes/query/modules/serialization.rb

################## CodeClimate's "inferred .codeclimate.yml" ##################
# Codeclimate generated this based on the Classic configuration above
#
# engines:
#   brakeman:
#     enabled: true
#   bundler-audit:
#     enabled: true
#   duplication:
#     enabled: true
#     config:
#       languages:
#       - ruby
#       - javascript
#       - python
#       - php
#   eslint:
#     enabled: true
#   fixme:
#     enabled: true
#   rubocop:
#     enabled: true
# ratings:
#   paths:
#   - Gemfile.lock
#   - "**.erb"
#   - "**.haml"
#   - "**.rb"
#   - "**.rhtml"
#   - "**.slim"
#   - "**.inc"
#   - "**.js"
#   - "**.jsx"
#   - "**.module"
#   - "**.php"
#   - "**.py"
#  exclude_paths:
#  - public/design_test/jquery-1.5.2.min.js
#  - app/assets/javascripts/bootstrap.js"
# 	"---
# engines:
#   brakeman:
#     enabled: true
#   bundler-audit:
#     enabled: true
#   duplication:
#     enabled: true
#     config:
#       languages:
#       - ruby
#       - javascript
#       - python
#       - php
#   eslint:
#     enabled: true
#   fixme:
#     enabled: true
#   rubocop:
#     enabled: true
# ratings:
#   paths:
#   - Gemfile.lock
#   - "**.erb"
#   - "**.haml"
#   - "**.rb"
#   - "**.rhtml"
#   - "**.slim"
#   - "**.inc"
#   - "**.js"
#   - "**.jsx"
#   - "**.module"
#   - "**.php"
#   - "**.py"
#  exclude_paths:
#  - public/design_test/jquery-1.5.2.min.js
#  - app/assets/javascripts/bootstrap.js"

